"""Point de vérité unique pour les constantes BVC Analyzer."""

# ── Noms officiels des sociétés cotées BVC ──────────────────────────────────
# Source de vérité : ces noms priment sur tout ce que retournent les scrapers.
COMPANY_NAMES: dict = {
    # ── Grandes capitalisations ─────────────────────────────────────────────
    "IAM":  "Itissalat Al-Maghrib",
    "ATW":  "Attijariwafa Bank",
    "BCP":  "Banque Centrale Populaire",
    "BOA":  "Bank of Africa",
    "CIH":  "Crédit Immobilier et Hôtelier",
    "CDM":  "Crédit du Maroc",
    "WAF":  "Wafa Assurance",
    "LHM":  "LafargeHolcim Maroc",
    "GAZ":  "Afriquia Gaz",
    "ATL":  "AtlantaSanad",
    "HPS":  "Hightech Payment System",
    "LBV":  "Label'Vie",
    "LES":  "Lesieur Cristal",
    "TQA":  "Taqa Morocco",
    "MRL":  "Marsa Maroc",
    "TMA":  "TotalEnergies Marketing Maroc",
    "CMT":  "Compagnie Minière de Touissit",
    "MNG":  "Managem",
    "SMI":  "S.M. Imiter",
    # ── Moyennes capitalisations ─────────────────────────────────────────────
    "AKD":  "Akdital",
    "ARD":  "Aradei Capital",
    "SAF":  "Saham Assurance",
    "OUL":  "Les Eaux Minérales d'Oulmès",
    "CIM":  "Ciments du Maroc",
    "CTM":  "Compagnie de Transports au Maroc",
    "ZLD":  "Zellidja",
    "SOT":  "Sothema",
    "MSA":  "Mutandis SCA",
    "ADI":  "Alliances Développement Immobilier",
    "ADH":  "Douja Promotion Addoha",
    "TGCC": "TGCC",                   # Travaux Généraux de Construction de Casablanca
    "CFGB": "CFG Bank",
    "CASH": "Cash Plus",
    "SGTM": "SGTM",
    "CMGP": "CMGP Group",
    "VCNE": "Vivo Energy Maroc",
    "RIS":  "Risma",
    "CSR":  "Cosumar",                # NE PAS CONFONDRE AVEC CIM (Ciments de l'Atlas)
    "SNA":  "Sonasid",
    "SRM":  "Réalisations Mécaniques",
    "RDS":  "Résidences Dar Saada",
    "ALU":  "Aluminium du Maroc",
    "MGL":  "Maghrebail",
    "DAR":  "Dari Couspate",
    "IMI":  "Immorente Invest",
    "DTT":  "Disty Technologies",
    # ── Petites capitalisations ──────────────────────────────────────────────
    "DSW":  "Disway",
    "MOX":  "Maghreb Oxygène",
    "STR":  "Stroc Industrie",
    "TIM":  "Timar",
    "SNP":  "SNEP",
    "SLM":  "Salafin",
    "JET":  "Jet Contractors",
    "M2M":  "M2M Group",
    "INV":  "Involys",
    "S2M":  "S.M. Monétique",
    "COL":  "Colorado",
    "AFM":  "AFMA",
    "AGM":  "Agma Lahlou-Tazi",
    "FNB":  "Fenie Brossette",
    "BAL":  "Balima",
    "NEJ":  "Auto Nejma",
    "HAL":  "Auto Hall",
    "BMC":  "BMCI",
    "CAR":  "Cartier Saada",
    "AFI":  "Afric Industries",
    "MIC":  "Microdata",
    "MUT":  "Mutandis SCA",
    "ENK":  "Enkaje",
    "EQD":  "Equity",
    "DHO":  "Delta Holding",
    "PPM":  "Unimer",
    "REB":  "Rebab Company",
    "SBS":  "Super Céréales",
    "STK":  "Stokvis Nord Afrique",
    "UNI":  "Unimer",
    "IBM":  "IB Maroc.com",
}

# ── Secteurs officiels ───────────────────────────────────────────────────────
COMPANY_SECTORS: dict = {
    "IAM":  "Télécommunications",
    "ATW":  "Banques",
    "BCP":  "Banques",
    "BOA":  "Banques",
    "CIH":  "Banques",
    "CDM":  "Banques",
    "WAF":  "Assurances",
    "SAF":  "Assurances",
    "LHM":  "Matériaux de construction",
    "CIM":  "Matériaux de construction",
    "GAZ":  "Distribution GPL",
    "TMA":  "Distribution pétrolière",
    "VCNE": "Distribution pétrolière",
    "ATL":  "Assurances",
    "HPS":  "Technologies & Paiement",
    "LBV":  "Grande distribution",
    "LES":  "Agroalimentaire",
    "CSR":  "Agroalimentaire",
    "OUL":  "Agroalimentaire",
    "BMC":  "Banques",
    "CAR":  "Agroalimentaire",
    "LHM":  "Matériaux de construction",
    "TQA":  "Énergie & Électricité",
    "MRL":  "Logistique portuaire",
    "CMT":  "Mines",
    "MNG":  "Mines",
    "SMI":  "Mines",
    "ZLD":  "Mines & Holdings",
    "MGL":  "Sociétés de financement",
    "SNA":  "Sidérurgie",
    "ALU":  "Métallurgie",
    "AKD":  "Santé",
    "SOT":  "Pharmacie",
    "ARD":  "Foncière cotée (REIT)",
    "IMI":  "Foncière cotée (REIT)",
    "RIS":  "Hôtellerie",
    "ADH":  "Immobilier",
    "ADI":  "Immobilier",
    "RDS":  "Immobilier",
    "DAR":  "Agroalimentaire et Production",
    "TGCC": "BTP & Construction",
    "SGTM": "BTP & Construction",
    "JET":  "BTP & Construction",
    "STR":  "BTP & Construction",
    "CFGB": "Banques",
    "CASH": "Transfert d'argent",
    "SLM":  "Crédit à la consommation",
    "CMGP": "Distribution matériaux",
    "SRM":  "Distribution industrielle",
    "STK":  "Distribution industrielle",
    "DSW":  "Distribution IT",
    "DTT":  "Distribution IT",
    "M2M":  "Technologies",
    "MIC":  "Technologies",
    "INV":  "Technologies",
    "HPS":  "Technologies & Paiement",
    "MSA":  "FMCG",
    "MUT":  "FMCG",
    "CTM":  "Transport",
    "TIM":  "Transport & Logistique",
    "MOX":  "Gaz industriels",
    "SNP":  "Chimie",
    "COL":  "Chimie",
    "AFM":  "Assurances courtage",
    "AGM":  "Assurances courtage",
    "FNB":  "Distributeurs",
    "EQD":  "Services financiers",
    "BAL":  "Assurances",
    "NEJ":  "Pétrole & Gaz",
    "HAL":  "Distribution automobile",
    "AFI":  "Industrie",
    "IBM":  "Technologies",
    "ENK":  "Services",
    "DHO":  "Holdings",
    "PPM":  "Papier & Emballage",
    "REB":  "Textile",
    "SBS":  "Agroalimentaire",
    "UNI":  "Agroalimentaire",
    "S2M":  "Technologies",
}

ISIN_MAP: dict = {
    "ADH": "MA0000011512", "AFM": "MA0000012296", "AFI": "MA0000012114",
    "GAZ": "MA0000010951", "AGM": "MA0000010944", "AKD": "MA0000012585",
    "ADI": "MA0000011819", "ALU": "MA0000010936", "ARD": "MA0000012460",
    "ATL": "MA0000011710", "ATW": "MA0000012445", "HAL": "MA0000010969",
    "NEJ": "MA0000011496", "BAL": "MA0000011991", "BOA": "MA0000012437",
    "BCP": "MA0000011884", "BMC": "MA0000010811", "CAR": "MA0000011868",
    "CDM": "MA0000010381", "CIH": "MA0000011454", "CIM": "MA0000010506",
    "CMT": "MA0000011793", "COL": "MA0000011934", "CSR": "MA0000012247",
    "CTM": "MA0000010340", "DAR": "MA0000011421", "DHO": "MA0000011850",
    "DTT": "MA0000012536", "DSW": "MA0000011637", "ENK": "MA0000011942",
    "EQD": "MA0000010357", "FNB": "MA0000011587", "HPS": "MA0000012619",
    "IBM": "MA0000011132", "IMI": "MA0000012387", "INV": "MA0000011579",
    "JET": "MA0000012080", "LBV": "MA0000011801", "LHM": "MA0000012320",
    "LES": "MA0000012031", "M2M": "MA0000011678", "MOX": "MA0000010985",
    "MGL": "MA0000011215", "MNG": "MA0000011058", "MRL": "MA0000012270",
    "IAM": "MA0000011488", "MIC": "MA0000012163", "MUT": "MA0000012395",
    "OUL": "MA0000010415", "PPM": "MA0000011660", "REB": "MA0000010993",
    "RDS": "MA0000012130", "RIS": "MA0000011140", "S2M": "MA0000011959",
    "SLM": "MA0000011611", "SAF": "MA0000011744", "SMI": "MA0000011041",
    "STK": "MA0000011843", "SNP": "MA0000011629", "MSA": "MA0000012312",
    "SON": "MA0000010019", "SOT": "MA0000012833", "SRM": "MA0000011538",
    "SBS": "MA0000010365", "STR": "MA0000011942", "TQA": "MA0000012213",
    "TGC": "MA0000012528", "TIM": "MA0000011686", "TMA": "MA0000012148",
    "UNI": "MA0000012023", "WAF": "MA0000010928", "ZLD": "MA0000011124",
    # IPOs
    "CFGB": "MA0000012627", "CMGP": "MA0000012718", "VCNE": "MA0000012759",
    "CASH": "MA0000012767", "SGTM": "MA0000012783",
    # Aliases utilisés par le pipeline v9
    "TGCC": "MA0000012528",  # alias de TGC
    "SNA":  "MA0000010019",  # alias de SON
}

TICKERS_DEFAUT: list = [
    "SMI", "MNG", "RIS", "RDS", "CSR", "SOT",
    "ADI", "MSA", "ADH", "TGC", "CMT", "SRM",
    "CFGB", "CMGP", "VCNE", "CASH", "SGTM",
]

IDB_NAME_MAP: dict = {"MTO": "CMT", "ALLI": "ADI", "TGC": "TGCC", "GTM": "SGTM"}

# 19 tickers actifs du pipeline BVC (MASI 1)
TICKERS_ACTIFS: list = [
    "ADH", "ADI", "AKD", "CASH", "CFGB", "CMGP", "CMT", "CSR",
    "MNG", "MSA", "RDS", "RIS", "SGTM", "SMI", "SNA", "SOT",
    "SRM", "TGCC", "VCNE",
]

# Tous les tickers uniques de la BVC (TGCC/SNA = formes canoniques, TGC/SON exclus)
# 77 valeurs — ordre : grande cap → moyenne → petite
TICKERS_ALL: list = [
    # Grandes capitalisations
    "IAM", "ATW", "BCP", "BOA", "CIH", "CDM", "WAF",
    "LHM", "GAZ", "ATL", "HPS", "LBV", "LES", "TQA", "MRL", "TMA",
    "CMT", "MNG", "SMI",
    # Moyennes capitalisations
    "AKD", "ARD", "SAF", "OUL", "CIM", "CTM", "ZLD",
    "SOT", "MSA", "ADI", "ADH", "TGCC", "CFGB", "CASH", "SGTM",
    "CMGP", "VCNE", "RIS", "CSR", "SNA", "SRM", "RDS",
    "ALU", "MGL", "DAR", "IMI", "DTT",
    # Petites capitalisations
    "DSW", "MOX", "STR", "TIM", "SNP", "SLM", "JET", "M2M",
    "INV", "S2M", "COL", "AFM", "AGM", "FNB", "BAL", "NEJ",
    "HAL", "BMC", "CAR", "AFI", "MIC", "MUT", "ENK", "EQD",
    "DHO", "PPM", "REB", "SBS", "STK", "UNI", "IBM",
]
