"""Alias de sociétés cotées, pour rattacher un article à un ticker.

Généré depuis les noms officiels : bvc_config.COMPANY_NAMES (référentiel
IDBourse validé le 02/07/2026) croisé avec la liste Wafabourse du 09/08/2026.

Le tagging fait de la correspondance EXACTE de sous-chaîne, jamais de
correspondance floue — mesurée le 09/08, celle-ci taggue 40 sociétés sur un
article traitant du chômage. En conséquence, un alias doit être discriminant :
les termes de moins de 5 caractères et les mots passe-partout (« maroc »,
« banque », « groupe », « equity »…) sont exclus à la génération.

Ne pas éditer à la main : relancer le générateur si un nom officiel change.
"""

TICKER_ALIASES = {
    "ADH": ["addoha", "douja promotion"],
    "ADI": ["alliance développement", "alliances"],
    "AFI": ["afi industrie", "afric industries"],
    "AFM": ["afma courtage", "afma maroc", "afma sa", "agence fassi maroc assurance", "groupe afma"],
    "AGM": ["agma assurances", "agma courtage", "agma lahlou tazi", "agma lahlou-tazi", "agma maroc", "agma sa", "groupe agma"],
    "AKD": ["akdital"],
    "ALU": ["alu maroc", "aluminium du maroc", "aluminium maroc"],
    "ARD": ["aradei"],
    "ATL": ["assurances atlanta", "atlanta assurances", "atlanta sanad", "atlantasanad", "atlasanad"],
    "ATW": ["attijari bank", "attijari wafa", "attijariwafa"],
    "BAL": ["balima"],
    "BCP": ["banque centrale populaire", "banques populaires", "bcp maroc", "bcp sa", "crédit populaire du maroc", "groupe banque populaire", "groupe bcp"],
    "BMC": ["banque marocaine pour le commerce et l'industrie", "bmci maroc", "bmci sa", "bnp paribas maroc", "groupe bmci"],
    "BOA": ["bank of africa", "banque of africa", "bmce bank", "boa maroc"],
    "CAR": ["cartier saada", "cartier saâda"],
    "CASH": ["cash plus"],
    "CDM": ["cdm bank", "cdm maroc", "credit du maroc", "crédit du maroc"],
    "CFGB": ["cfg bank", "cfg capital bank", "cfg maroc", "cfgb maroc"],
    "CIH": ["cih bank", "cih banque", "cih maroc", "cih sa", "credit immobilier hotelier", "crédit immobilier et hôtelier", "groupe cih"],
    "CIM": ["cim maroc", "ciments du maroc", "ciments maroc"],
    "CMGP": ["cmgp distribution", "cmgp group", "cmgp maroc", "cmgp matériaux", "cmgp sa", "groupe cmgp"],
    "CMT": ["cmt maroc", "cmt sa", "groupe cmt", "touissit"],
    "COL": ["colorado"],
    "CSR": ["compagnie sucrière marocaine", "cosumar"],
    "CTM": ["compagnie de transports au maroc", "ctm bus", "ctm maroc", "ctm sa", "ctm transport", "ctm voyages", "groupe ctm"],
    "DAR": ["couspate"],
    "DHO": ["delta holding", "delta industries"],
    "DSW": ["dis way maroc", "disway"],
    "DTT": ["disty tech", "dtt distribution"],
    "ENK": ["ennakl"],
    "EQD": ["eqdom"],
    "FNB": ["fenie brossette", "fenie-brossette", "fenié brossette", "fénie brossette"],
    "GAZ": ["afriquia gas", "afriquia gaz", "gaz afriquia"],
    "HAL": ["auto hall", "auto-hall", "autohall"],
    "HPS": ["groupe hps", "high tech payment", "hightech payment system", "hps maroc", "hps payment", "hps sa", "hps worldwide"],
    "IAM": ["iam maroc", "iam telecom", "itissalat al maghrib", "itissalat al-maghrib", "maroc telecom", "maroc télécoms"],
    "IBM": ["ib maroc", "ib-maroc.com", "ib-maroccom", "ibmaroc"],
    "IMI": ["immorente"],
    "INV": ["involys"],
    "JET": ["jet btp", "jet contractor"],
    "LBV": ["label vie", "label'vie", "labelvie"],
    "LES": ["lesieur cristal", "lesieur maroc", "lesieur-cristal"],
    "LHM": ["holcim maroc", "lafarge maroc", "lafargeholcim", "lhm maroc"],
    "M2M": ["groupe m2m", "m2m group", "m2m maroc", "m2m sa", "m2m technologies"],
    "MGL": ["leasing maghreb", "maghrebail"],
    "MIC": ["microdata"],
    "MNG": ["managem"],
    "MOX": ["maghreb oxy", "mox gaz"],
    "MRL": ["maroc leasing", "maroc-leasing", "maroclease"],
    "MSA": ["marsa maroc", "marsa portuaire", "marsa tanger", "sodep marsa"],
    "MUT": ["mutandis"],
    "NEJ": ["auto nejma", "nejma auto"],
    "OUL": ["oulmes", "oulmès"],
    "PPM": ["promopharm"],
    "RDS": ["dar saada", "dar saâda"],
    "REB": ["rebab"],
    "RIS": ["risma", "résidences touristiques de montagne"],
    "S2M": ["groupe s2m", "s.m monetique", "s.m monétique", "s.m. monétique", "s2m group", "s2m maroc", "s2m sa", "sm monétique", "soft mobile maroc"],
    "SAF": ["saham assurance", "saham finances", "saham maroc", "sanlam assurance", "sanlam maroc"],
    "SBS": ["boissons du maroc", "brasseries du maroc", "groupe sbm", "sbm brasseries", "sbm maroc", "sbm sa"],
    "SGTM": ["groupe sgtm", "sgtm maroc", "sgtm sa", "sgtm travaux", "société générale de travaux du maroc"],
    "SLM": ["salafin"],
    "SMI": ["groupe smi", "imiter mines", "metallurgique imiter", "s.m. imiter", "sm imiter", "smi maroc", "smi sa", "smiter", "société métallurgique imiter"],
    "SNA": ["société nationale de sidérurgie", "sonasid"],
    "SNP": ["groupe snep", "snep chimie", "snep industrie", "snep maroc", "snep sa", "société nationale d'électrolyse et de pétrochimie"],
    "SOT": ["sothema"],
    "SRM": ["groupe srm", "realisations mecaniques", "réalisations mécaniques", "srm industrie", "srm maroc", "srm sa"],
    "STK": ["stokvis"],
    "STR": ["groupe stroc", "stroc construction", "stroc industrie", "stroc maroc"],
    "TGCC": ["groupe tgcc", "tgcc construction", "tgcc maroc", "tgcc sa", "travaux généraux de construction de casablanca"],
    "TIM": ["timar"],
    "TMA": ["total energies maroc", "total marketing maroc", "total maroc", "totalenergies"],
    "TQA": ["jordan low electricity", "taqa energy", "taqa maroc", "taqa morocco", "taqa power"],
    "UNI": ["unimer"],
    "VCNE": ["vicenne"],
    "WAF": ["wafa assurance", "wafa insurance", "wafassurance"],
    "ZLD": ["zellidja"],
}
